project:
  type: book
  output-dir: docs

book:
  title: Regressão Linear
  author: "Fernando Náufel"
  date: now
  output-file: regressao-linear
  search: true
  repo-url: https://github.com/fnaufel/regressao-linear
  repo-branch: master
  repo-actions: [edit]
  # downloads: [pdf]
  date-format: "DD/MM/YYYY HH:mm"
  sharing: 
    - twitter
    - facebook
    - linkedin
  chapters:
    - index.qmd
    - simples.qmd
    - references.qmd

bibliography: bibliography.bib
csl: universidade-do-porto-faculdade-de-engenharia-chicago-pt-crono.csl

comments:
  hypothesis: true

format:
  html:
    toc-depth: 3
    number-depth: 2
    theme: 
      - journal
      - _custom.scss
    df-print: paged
    code-link: true
    code-copy: true
    code-tools: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/fnaufel\.github\.io
  # pdf:
  #   documentclass: scrreprt
  #   toc-depth: 3
  #   number-depth: 3
  #   fig-pos: htb
  #   keep-tex: true
  #   # filters: 
  #   #   - filters/dollar.py3
  #   #   - filters/hl.py3
  #   include-in-header: 
  #     - _preamble.tex
  #   include-before-body:  
  #     - _before-body.tex

